# run again.  Do not edit this file unless you know what you are doing.
import json
from pathlib import Path
from PySide6 import QtCore, QtWidgets
from PySide6.QtCore import Qt
from videotrans.configure.config import tr,ROOT_DIR, params,settings
from videotrans.configure.contants import GEMINI_TTS_MODELS
from videotrans.util.help_misc import open_url


class Ui_geminiform(object):
    def setupUi(self, geminiform):
        self.has_done = False
        self.geminiform = geminiform
        geminiform.setObjectName("geminiform")
        geminiform.setWindowModality(QtCore.Qt.NonModal)
        geminiform.resize(600, 550)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Fixed, QtWidgets.QSizePolicy.Fixed)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(geminiform.sizePolicy().hasHeightForWidth())
        geminiform.setSizePolicy(sizePolicy)
        geminiform.setMaximumSize(QtCore.QSize(600, 750))

        v1 = QtWidgets.QVBoxLayout(geminiform)

        # === Auth Type Selection ===
        h_auth_type = QtWidgets.QHBoxLayout()
        self.label_auth_type = QtWidgets.QLabel()
        self.label_auth_type.setMinimumSize(QtCore.QSize(0, 35))
        self.label_auth_type.setObjectName("label_auth_type")
        self.label_auth_type.setText(tr("Auth Type"))

        self.radio_api_key = QtWidgets.QRadioButton(tr("API Key (AI Studio)"))
        self.radio_api_key.setChecked(True)
        self.radio_vertex = QtWidgets.QRadioButton(tr("Vertex AI (Service Account)"))

        self.auth_group = QtWidgets.QButtonGroup(geminiform)
        self.auth_group.addButton(self.radio_api_key, 0)
        self.auth_group.addButton(self.radio_vertex, 1)

        h_auth_type.addWidget(self.label_auth_type)
        h_auth_type.addWidget(self.radio_api_key)
        h_auth_type.addWidget(self.radio_vertex)
        h_auth_type.addStretch()
        v1.addLayout(h_auth_type)

        # === API Key fields (shown for api_key mode) ===
        self.widget_api_key = QtWidgets.QWidget()
        layout_api_key = QtWidgets.QVBoxLayout(self.widget_api_key)
        layout_api_key.setContentsMargins(0, 0, 0, 0)

        h1 = QtWidgets.QHBoxLayout()
        self.label_2 = QtWidgets.QLabel()
        self.label_2.setMinimumSize(QtCore.QSize(0, 35))
        self.label_2.setSizeIncrement(QtCore.QSize(0, 35))
        self.label_2.setObjectName("label_2")
        self.gemini_key = QtWidgets.QLineEdit()
        self.gemini_key.setMinimumSize(QtCore.QSize(0, 35))
        self.gemini_key.setObjectName("gemini_key")
        h1.addWidget(self.label_2)
        h1.addWidget(self.gemini_key)
        layout_api_key.addLayout(h1)
        v1.addWidget(self.widget_api_key)

        # === Vertex AI fields (shown for vertex mode) ===
        self.widget_vertex = QtWidgets.QWidget()
        self.widget_vertex.setVisible(False)
        layout_vertex = QtWidgets.QVBoxLayout(self.widget_vertex)
        layout_vertex.setContentsMargins(0, 0, 0, 0)

        hv_json = QtWidgets.QHBoxLayout()
        self.label_vertex_json = QtWidgets.QLabel()
        self.label_vertex_json.setMinimumSize(QtCore.QSize(0, 35))
        self.label_vertex_json.setObjectName("label_vertex_json")
        self.label_vertex_json.setText(tr("Service Account JSON"))
        self.vertex_json_path = QtWidgets.QLineEdit()
        self.vertex_json_path.setMinimumSize(QtCore.QSize(0, 35))
        self.vertex_json_path.setObjectName("vertex_json_path")
        self.vertex_json_path.setPlaceholderText(tr("Path to service-account.json"))
        self.btn_browse_json = QtWidgets.QPushButton("...")
        self.btn_browse_json.setMaximumSize(QtCore.QSize(35, 35))
        self.btn_browse_json.setObjectName("btn_browse_json")
        hv_json.addWidget(self.label_vertex_json)
        hv_json.addWidget(self.vertex_json_path)
        hv_json.addWidget(self.btn_browse_json)
        layout_vertex.addLayout(hv_json)

        hv_project = QtWidgets.QHBoxLayout()
        self.label_vertex_project = QtWidgets.QLabel()
        self.label_vertex_project.setMinimumSize(QtCore.QSize(0, 35))
        self.label_vertex_project.setObjectName("label_vertex_project")
        self.label_vertex_project.setText(tr("Project ID"))
        self.vertex_project = QtWidgets.QLineEdit()
        self.vertex_project.setMinimumSize(QtCore.QSize(0, 35))
        self.vertex_project.setObjectName("vertex_project")
        self.vertex_project.setPlaceholderText("full-video-499000")
        hv_project.addWidget(self.label_vertex_project)
        hv_project.addWidget(self.vertex_project)
        layout_vertex.addLayout(hv_project)

        hv_location = QtWidgets.QHBoxLayout()
        self.label_vertex_location = QtWidgets.QLabel()
        self.label_vertex_location.setMinimumSize(QtCore.QSize(0, 35))
        self.label_vertex_location.setObjectName("label_vertex_location")
        self.label_vertex_location.setText(tr("Location"))
        self.vertex_location = QtWidgets.QLineEdit()
        self.vertex_location.setMinimumSize(QtCore.QSize(0, 35))
        self.vertex_location.setObjectName("vertex_location")
        self.vertex_location.setPlaceholderText("us-central1")
        self.vertex_location.setText("us-central1")
        hv_location.addWidget(self.label_vertex_location)
        hv_location.addWidget(self.vertex_location)
        layout_vertex.addLayout(hv_location)

        v1.addWidget(self.widget_vertex)

        h2 = QtWidgets.QHBoxLayout()
        self.label_3 = QtWidgets.QLabel()
        self.label_3.setObjectName("label_3")
        self.model = QtWidgets.QComboBox()
        self.model.setMinimumSize(QtCore.QSize(0, 35))
        self.model.setObjectName("model")
        h2.addWidget(self.label_3)
        h2.addWidget(self.model)
        v1.addLayout(h2)
        
        
        h_token=QtWidgets.QHBoxLayout()
        label_token = QtWidgets.QLabel()
        label_token.setObjectName("label_token")
        label_token.setText('Max Token')
        self.gemini_maxtoken = QtWidgets.QLineEdit()
        self.gemini_maxtoken.setObjectName("gemini_maxtoken")
        
        h_token.addWidget(label_token)
        h_token.addWidget(self.gemini_maxtoken)
        v1.addLayout(h_token)
        

        self.label_allmodels = QtWidgets.QLabel()
        self.label_allmodels.setObjectName("label_allmodels")
        self.label_allmodels.setText(
            tr("Fill in all available models, separated by commas. After filling in, you can select them above"))
        self.label_allmodels.setStyleSheet("color:#999")

        self.edit_allmodels = QtWidgets.QPlainTextEdit()
        self.edit_allmodels.setObjectName("edit_allmodels")
        v1.addWidget(self.label_allmodels)
        v1.addWidget(self.edit_allmodels)

        self.label_4 = QtWidgets.QLabel()
        self.label_4.setObjectName("label_4")
        self.gemini_template = QtWidgets.QPlainTextEdit()
        self.gemini_template.setObjectName("gemini_template")
        self.gemini_template.setReadOnly(True)
        v1.addWidget(self.label_4)
        v1.addWidget(self.gemini_template)

        self.label_srt = QtWidgets.QLabel()
        self.label_srt.setObjectName("label_srt")

        hrecogn = QtWidgets.QHBoxLayout()
        hrecogn.addWidget(self.label_srt)

        v1.addLayout(hrecogn)

        self.gemini_srtprompt = QtWidgets.QLineEdit()
        self.gemini_srtprompt.setObjectName("gemini_srtprompt")
        self.gemini_srtprompt.setReadOnly(True)
        self.gemini_srtprompt.setDisabled(True)
        self.gemini_srtprompt.setText(f'{ROOT_DIR}/videotrans/prompts/recogn/gemini_recogn.txt')

        v1.addWidget(self.gemini_srtprompt)

        h2ttsmodel = QtWidgets.QHBoxLayout()
        self.label_ttsmodel = QtWidgets.QLabel()
        self.label_ttsmodel.setObjectName("label_ttsmodel")
        self.label_ttsmodel.setText('TTS model')

        self.ttsmodel = QtWidgets.QComboBox()
        self.ttsmodel.setMinimumSize(QtCore.QSize(0, 35))
        self.ttsmodel.setObjectName("ttsmodel")
        self.ttsmodel.addItems(GEMINI_TTS_MODELS.split(','))
        h2ttsmodel.addWidget(self.label_ttsmodel)
        h2ttsmodel.addWidget(self.ttsmodel)
        v1.addLayout(h2ttsmodel)

        h3 = QtWidgets.QHBoxLayout()
        self.set_gemini = QtWidgets.QPushButton()
        self.set_gemini.setMinimumSize(QtCore.QSize(0, 35))
        self.set_gemini.setObjectName("set_gemini")

        self.test = QtWidgets.QPushButton()
        self.test.setObjectName("test")

        help_btn = QtWidgets.QPushButton()
        help_btn.setMinimumSize(QtCore.QSize(0, 35))
        help_btn.setStyleSheet("background-color: rgba(255, 255, 255,0)")
        help_btn.setObjectName("help_btn")
        help_btn.setCursor(Qt.PointingHandCursor)
        help_btn.setText(tr("Fill out the tutorial"))
        help_btn.clicked.connect(lambda: open_url(url='https://pyvideotrans.com/gemini'))

        h3.addWidget(self.set_gemini)
        h3.addWidget(self.test)
        h3.addWidget(help_btn)
        v1.addLayout(h3)
        self.gemini_template.setPlainText(tr("Prompt: Please open the {} file directly to modify it", 'gemini', 'gemini'))
        self.geminiform = geminiform
        geminiform.setWindowTitle("Gemini AI")
        self.retranslateUi()
        QtCore.QMetaObject.connectSlotsByName(geminiform)
        # Connect Vertex AI signals
        self.radio_api_key.toggled.connect(self.toggle_auth_widgets)
        self.radio_vertex.toggled.connect(self.toggle_auth_widgets)
        self.btn_browse_json.clicked.connect(self.browse_json)


    def toggle_auth_widgets(self):
        is_vertex = self.radio_vertex.isChecked()
        self.widget_api_key.setVisible(not is_vertex)
        self.widget_vertex.setVisible(is_vertex)
        # Adjust window size
        if is_vertex:
            self.geminiform.resize(600, 700)
        else:
            self.geminiform.resize(600, 550)

    def browse_json(self):
        from PySide6.QtWidgets import QFileDialog
        fpath, _ = QFileDialog.getOpenFileName(
            self.geminiform, tr("Select service account JSON"),
            "", "JSON Files (*.json);;All Files (*)"
        )
        if fpath:
            self.vertex_json_path.setText(fpath)
            # Auto-read project_id
            try:
                data = json.loads(Path(fpath).read_text(encoding="utf-8"))
                if 'project_id' in data:
                    self.vertex_project.setText(data['project_id'])
            except Exception:
                pass

    def update_ui(self):
        allmodels_str = settings.get('gemini_model','')
        allmodels = str(settings.get('gemini_model','')).split(',')
        self.model.clear()
        self.model.addItems(allmodels)
        self.edit_allmodels.setPlainText(allmodels_str)
        self.gemini_key.setText(str(params.get("gemini_key",'')))
        self.model.setCurrentText(params.get("gemini_model",''))

        self.gemini_maxtoken.setText(str(params.get("gemini_maxtoken",'16384')))

        self.ttsmodel.setCurrentText(params.get("gemini_ttsmodel",''))

        # Vertex AI fields
        auth_type = params.get('gemini_auth_type', 'api_key')
        if auth_type == 'vertex':
            self.radio_vertex.setChecked(True)
        else:
            self.radio_api_key.setChecked(True)
        self.vertex_json_path.setText(str(params.get('gemini_vertex_json', '')))
        self.vertex_project.setText(str(params.get('gemini_vertex_project', '')))
        self.vertex_location.setText(str(params.get('gemini_vertex_location', 'us-central1')))
        self.toggle_auth_widgets()

    def retranslateUi(self):
        
        self.gemini_template.setPlaceholderText("prompt")
        self.label_4.setText(
            tr("{lang} represents the target language name, do not delete it."))
        self.label_4.setStyleSheet("color: #999;")
        self.set_gemini.setText(tr("Save"))
        self.test.setText(tr("Test"))
        self.gemini_key.setPlaceholderText("secret key")
        self.label_2.setText("Gemini  Key ")
        self.label_auth_type.setText(tr("Auth Type"))
        self.radio_api_key.setText(tr("API Key (AI Studio)"))
        self.radio_vertex.setText(tr("Vertex AI (Service Account)"))
        self.label_srt.setText(
            tr("Prompt for subtitles when converting audio to video"))
        self.label_srt.setStyleSheet("color: #999;")
        self.label_3.setText(tr("Select model"))
